spring:
  redis:
    database: 0
    host: 192.168.169.2
    port: 36379
  cloud:
    gateway:
      default-filters:
        # 也可使用 RewritePath 代替 StripPrefix
        - StripPrefix=1
        - AddRequestHeader=X-test, hello
      nacos-metadata-balancer:
        enabled: true
        key: VERSION
      security-http-api:
        enabled: true
        aes-key: 076776ef4b774ef5
      routes:
        - id: ipp-auth-server
          uri: lb://ipp-auth-server
          predicates:
            - Path=/auth/**
          filters:
            # AccessForbidden 禁止访问过滤器，匹配路径成功后返回403
            - AccessForbidden=/test/redis/**
            - AddRequestParameter=server, auth
        - id: ipp-product-server
          uri: lb://ipp-product-server
          predicates:
            - Path=/product/**
          filters:
            - AddRequestParameter=server, product
        - id: ipp-content-server
          uri: lb://ipp-content-server
          predicates:
            - Path=/content/**
          filters:
            - AddRequestParameter=server, content
logging:
  level:
    org.springframework.cloud.gateway: debug