spring:
  security:
    oauth2:
      resource-server:
        ignore-url:
          - /favicon.ico
          - /actuator/**
          - /documentation/**
          - /doc.html**
          - /test/**
          - /reg/**

  redis:
    database: 0
    host: xxx.xxx.xxx.xxx
    port: 36379
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xxx
    password: xxx
    url: jdbc:mysql://xxx.xxx.xxx.xxx:33306/ipp-cover-auth?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
    druid:
      initial-size: 2
      max-active: 30
      min-idle: 2
      max-wait: 1234
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 5
      validation-query: select 1
      validation-query-timeout: 1
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 10000
      min-evictable-idle-time-millis: 30001
      async-close-connection-enable: true

springfox:
  documentation:
    provider:
      base-package: "net.manbucy.ipp.cover.auth"
      group-name: "ipp-auth-api"
      version: "V3"
      context: "auth"

verify-code:
  limit:
    repeat-limit-time: 60
    code-expire-time: 300
    max-limit-time: 3600
    max-limit-count: 5
mail-server:
  host: smtp.ym.163.com
  port: 25
  auth: true
  from: 子虚物优科技<ipp@manbucy.net>
  user: ipp@manbucy.net
  pass: www.1994
logging:
  level:
    org.springframework.security: debug